openapi: 3.2.0
info:
  version: '1.0'
  title: Redocly Scout agent Health API
  description: Scout Worker API.
  termsOfService: https://redocly.com/subscription-agreement
  contact:
    name: Redocly Support
    email: team@redocly.com
    url: https://github.com/Redocly/redocly
  license:
    name: Redocly
    url: https://redocly.com/subscription-agreement
servers:
- url: '{host}'
  variables:
    host:
      default: http://localhost
      description: Server host.
tags:
- name: Health
  description: Operations related to health checks.
paths:
  /health:
    get:
      tags:
      - Health
      security: []
      summary: Get health status
      operationId: health
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  responses:
    BadRequest:
      description: Bad Request.
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              type:
                type: string
                description: Error type.
                example: about:blank
              title:
                type: string
                description: Error title.
                example: Unauthorized
              status:
                type: integer
                description: HTTP status code generated by the origin server for this occurrence of the problem.
                example: 401
              detail:
                type: string
                description: A human-readable message with more details.
                example: The request doesn't contain a GitHub signature
            required:
            - detail
    InternalServerError:
      description: Internal Server Error.
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              type:
                type: string
                description: Error type.
                example: about:blank
              title:
                type: string
                description: Error title.
                example: Internal server error
              status:
                type: integer
                description: HTTP status code generated by the origin server for this occurrence of the problem.
                example: 500
              detail:
                type: string
                description: A human-readable message with more details.
                example: Disk space is full
              event:
                type: string
                description: Type of incoming webhook event.
                example: push
            required:
            - detail
  schemas:
    Health:
      type: object
      properties:
        scout:
          type: string
          const: ok
          readOnly: true
          description: Scout health status.
      required:
      - scout
  securitySchemes:
    GithubApiKey:
      type: apiKey
      in: header
      name: x-hub-signature-256
    GitlabApiKey:
      type: apiKey
      in: header
      name: x-gitlab-token
x-pagination: none
