openapi: 3.2.0
info:
  version: '1.0'
  title: Redocly Scout Status API
  termsOfService: https://redocly.com/subscription-agreement
  contact:
    name: API Support
    email: team@redocly.com
  license:
    name: Redocly
    url: https://redocly.com/subscription-agreement
  description: Operations related to status.
servers:
- url: https://{host}/api
  variables:
    host:
      default: app.cba.au.redocly.com
      description: Server host.
  description: Production main server.
security:
- UserCookie: []
tags:
- name: Status
  description: Operations related to status.
paths:
  /orgs/{orgId}/projects/{projectId}/scout/status:
    post:
      tags:
      - Status
      security:
      - ApiKey: []
      summary: Push status
      description: Scout uses this to periodically report it's status back to main api.
      operationId: reportStatus
      parameters:
      - $ref: '#/components/parameters/X-Redocly-Scout-Version'
      - $ref: '#/components/parameters/OrgId'
      - $ref: '#/components/parameters/ProjectId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Status'
      responses:
        '204':
          description: No content.
        '400':
          $ref: '#/components/responses/BadRequestError'
components:
  parameters:
    ProjectId:
      name: projectId
      description: Project ID.
      required: true
      in: path
      schema:
        type: string
        example: my-project
    OrgId:
      name: orgId
      description: Organization ID.
      required: true
      in: path
      schema:
        type: string
        example: acme-inc
    X-Redocly-Scout-Version:
      name: x-redocly-scout-version
      description: Scout version.
      required: false
      in: header
      schema:
        type: string
        example: 1.0.0
  schemas:
    Problem:
      type: object
      title: Problem
      properties:
        type:
          type: string
          format: uri-reference
          description: 'URI reference that uniquely identifies the problem type only in the context of the provided API. Opposed to the specification in RFC 9457 (formerly RFC 7807), it is neither recommended to be dereferenceable and point to a human-readable documentation nor globally unique for the problem type.

            '
          default: about:blank
          example: /some/uri-reference
        title:
          type: string
          description: 'Short summary of the problem type. Written in English and readable for engineers, usually not suited for non technical stakeholders and not localized.

            '
          example: some title for the error situation
        status:
          type: integer
          format: int32
          description: 'HTTP status code generated by the origin server for this occurrence of the problem.

            '
          minimum: 100
          exclusiveMaximum: 600
          example: 400
        detail:
          type: string
          description: 'Human readable explanation specific to this occurrence of the problem that is helpful to locate the problem and give advice on how to proceed. Written in English and readable for engineers, usually not suited for non technical stakeholders and not localized.

            '
          example: some description for the error situation
        instance:
          type: string
          format: uri-reference
          description: 'URI reference that identifies the specific occurrence of the problem, e.g. by adding a fragment identifier or sub-path to the problem type. May be used to locate the root of this problem in the source code.

            '
          example: /some/uri-reference#specific-occurrence-context
        object:
          type: string
          const: problem
      required:
      - type
      - title
      - status
      - object
    Status:
      type: object
      properties:
        hostname:
          type: string
          description: Hostname of Scout instance.
        pid:
          type: integer
          description: Process ID.
        version:
          type: string
          description: Scout version.
        disk:
          type: object
          description: Disk usage.
          properties:
            size:
              type: integer
              description: Total disk size.
            used:
              type: integer
              description: Used disk size.
            available:
              type: integer
              description: Available disk size.
            unit:
              type: string
              description: Disk size unit.
              enum:
              - B
              - KB
              - MB
              - GB
              - TB
              example: MB
          required:
          - size
          - used
          - available
          - unit
        jobs:
          type: object
          description: Scout jobs.
          properties:
            active:
              type: integer
              description: Number of active jobs.
            max:
              type: integer
              description: Maximum number of jobs.
          required:
          - active
          - max
      required:
      - hostname
      - pid
      - version
      - disk
      - jobs
  responses:
    BadRequestError:
      description: Bad Request.
      content:
        application/problem+json:
          schema:
            description: Invalid credentials.
            $ref: '#/components/schemas/Problem'
  securitySchemes:
    UserCookie:
      type: apiKey
      in: cookie
      name: accessToken
      description: Default authentication scheme for interaction between browser and API.
    ApiKey:
      type: http
      scheme: bearer
      description: 'API key is required to access the API.

        You can get your API key from the [BlueHarvest dashboard](https://app.blueharvest.cloud).'
x-pagination: none
